### ISSUE TITLE
Tweaked styles to blend in a bit more.

### ISSUE THREAD

**Issue by dustindowell22** [dnbard/extensions-toolbar#14]
Not really sure how or if I should do a pull request for this, but I tweaked some styles to make it blend in a bit more with the rest of the toolbar.

![image](http://cl.ly/image/2K24120b2z2t/Screen%20Shot%202015-01-25%20at%2012.54.22%20PM.png)

Modified / Added Classes:

```scss
.ext-icon {
  width: 24px;
  height: 24px;
  margin-right: 9px;
  vertical-align: top;
  text-align: center;
}

.extension-toolbar {
  display: inline-block !important;
  height: 24px;
  margin-right: 12px;
  padding: 0 3px;
  border-right: 1px solid #343434;
}
```

Then I think you can remove line 37 and 38 out of `main.js`. These lines: 

```js
  extension.css('width', '24px');
  extension.css('height', '24px');
```
